/** Admitted upstream geometry; no React or browser work occurs at import time. */
export {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  BellRing,
  Bot,
  Box,
  Boxes,
  Braces,
  Building2,
  CalendarClock,
  CalendarRange,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleGauge,
  CirclePause,
  CirclePlay,
  CircleSlash2,
  CircleX,
  ClipboardCheck,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerUpRight,
  Cpu,
  CreditCard,
  Diff,
  ExternalLink,
  FileJson2,
  FileText,
  Filter,
  Flag,
  FlaskConical,
  FolderKanban,
  FolderPlus,
  Gauge,
  GitBranch,
  GitFork,
  Globe2,
  Grid2X2,
  HardDrive,
  Info,
  KeyRound,
  LayoutGrid,
  Library,
  Lightbulb,
  Link2,
  List,
  ListChecks,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Maximize2,
  Menu,
  MessageCircleMore,
  MessageSquareText,
  Moon,
  Network,
  OctagonX,
  Package,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  Paperclip,
  PauseCircle,
  Pencil,
  Play,
  Plus,
  Power,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  ScrollText,
  Search,
  Send,
  ServerCog,
  Settings,
  Settings2,
  ShieldCheck,
  Sparkles,
  Square,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  Unlink,
  UserPlus,
  UserRound,
  WandSparkles,
  Waypoints,
  Workflow,
  Wrench,
  X,
  Zap,
} from "lucide";

/** Framework-independent shape contract; geometry remains upstream-owned. */
export type IconData = readonly [
  tag: string,
  attributes: Readonly<Record<string, string | number>>,
  children?: readonly (readonly [tag: string, attributes: Readonly<Record<string, string | number>>])[],
];
export const iconAttributes = {
  xmlns: "http://www.w3.org/2000/svg",
  width: 16,
  height: 16,
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  "stroke-width": 2,
  "stroke-linecap": "round",
  "stroke-linejoin": "round",
} as const;
